config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  devise_for :users, skip: [:sessions], :controllers => {passwords: "passwords", registrations: "users"}
  as :user do
    get "/login", to: "sessions#new", as: :new_user_session
    post "/login", to: "sessions#create", as: :user_session
    delete "/logout", to: "sessions#destroy", as: :destroy_user_session
  end

  as :user do
    delete "/users/:id", to: "users#destroy", as: :user
    patch "/users/:id/block", to: "users#block_user", as: :block_user
    get "/trainer", to: "users#index", as: :user_trainer
    get "/trainee", to: "users#index", as: :user_trainee
    get "/users/:id", to: "users#show"
    # delete "/logout", to: "sessions#destroy", as: :destroy_user_session
  end

  as :course do
    get "/mycourse/:id", to: "trainee/courses#show", as: :trainee_course_view
    get "/mycourses", to: "trainee/courses#index"
    get "/course/new", to: "courses#new", as: :new_course
    patch "/courses/:id/block", to: "courses#block_course", as: :block_course
    get "/courses/:id", to: "courses#show"
    as :subjects do
      get "/mycourse/:course_id/subjects/:subject_id", to: "trainee/subjects#show", as: :show_subject_in_course
      get "/courses/:course_id/subjects/:subject_id", to: "subjects#show_subject_in_course", as: :show_subject_in_course_trainer
    end
  end

  patch "/update_progress/:id", to: "trainee/user_tasks#update", as: :user_task
  root to: "static_pages#home"
  get "/introduction", to: "trainee/candidates#new"
  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"
  resources :subjects
  resources :candidates, except: %i(new create)
  post "candidates", to: "trainee/candidates#create"
  resources :detail_links
  resources :courses
  resources :course_subjects, only: [:create, :update, :destroy, :index]
  resources :user_courses, only: [:create, :update, :destroy, :index]
  patch "/define_action", to: "course_subjects#define_action"
  post "/del_user_courses", to: "user_courses#del_user_courses"
  post "/del_course_subject", to: "course_subjects#del_course_subjects"
  get "/profiles/:id", to: "trainee/users#show", as: :profile
  get "/profiles/:id/edit", to: "profiles#edit", as: :edit_profile
  put "profiles/:id", to: "profiles#update", as: :update_profile
  patch "profiles/:id", to: "profiles#updateAvatar", as: :avatar
  get "/courses/status", to: "courses#change_status", as: :course_status
end

app/controllers/courses_controller.rb
  class CoursesController < ApplicationController
  before_action :logged_in_user
  before_action :verify_suppervisor_true
  load_and_authorize_resource param_method: :course_params

  def index
    unless user_signed_in?
      redirect_to "/introduction"
    else
      unless current_user.suppervisor?
        @courses = current_user.courses
      else
        case params[:option]
        when "1"
          @courses = Course.owner(current_user.id).page params[:page]
        when "2"
          @courses = current_user.courses.page params[:page]
        else
          @courses = Course.all.page params[:page]
        end
      end
    end
  end

  def show
    @course_subjects = @course.course_subjects
    @trainers = @course.users.trainers.alphabet_name
    @trainees = @course.users.trainees.alphabet_name
  end

  def edit; end

  def update
    if @course.update_attributes course_params
      if params[:course][:status] == "finish"
        @course.update_attributes date_end: Time.zone.today
        @course.course_subjects.each do |cs|
          cs.update_attributes status: "finish"
          cs.user_subjects.each do |us|
            unless us.finish?
              us.update_attributes status: "block"
            end
          end
        end
      end
      flash[:success] = "Success! This course has been update successful"
      redirect_to @course
    else
      render :edit
    end
  end

  def new
    @course = Course.new
  end

  def create
    if @course.save
      flash[:success] = "Success! This course has been create successful"
      redirect_to courses_path
    else
      render :new
    end
  end

  def destroy
    if @course.init?
      if @course.destroy
        @mes_success = "Delete #{@course.name} successful"
      else
        @mes_fail = "Delete #{@course.name} unsuccessful"
      end
    else
      @mes_fail = "#{@course.name} had been active, delete is unpermitted"
    end
  end

  def block_course
    if @course.update_attributes status: params[:status]
      if params[:status] == "block"
        @mes_success = "#{@course.name} has been locked"
      else
        @mes_success = "#{@course.name} has been unlocked"
      end
    else
      @mes_danger = "WARNING! HAS AN ERROR"
    end
  end

  private

  def course_params
    params[:course][:date_start] = Date.strptime(params[:course][:date_start], "%m/%d/%Y")
    params.require(:course).permit(:name, :description, :users_id, :program, :training_standard,
      :date_start, :avatar, :banner)
  end

  def load_trainers course
    @trainers = course.users.with_suppervisor.alphabet_name
    @all_trainers = User.with_suppervisor.alphabet_name
    @all_trainers = @all_trainers.without_course course if @trainers.present?
  end

  def load_trainees course
    @trainees = course.users.without_suppervisor.alphabet_name
    @all_trainees = User.without_suppervisor.alphabet_name
    @all_trainees = @all_trainees.without_course course if @trainees.present?
  end

  def load_subjects course
    @subjects = course.subjects
    @all_subjects = Subject.all
    @all_subjects = @all_subjects.without_course course if @subjects.present?
  end

end

app/controllers/trainee/candidates_controller.rb
class Trainee::CandidatesController < ApplicationController
  skip_before_action :verify_authenticity_token
  layout "layout2"

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new params_candidate
    if @candidate.save
      @mes_success = "Successfully register!"
      RegisterInternshipMailer.notification_register_success(params).deliver_now
    end
  end

  private

  def params_candidate
    params.require(:candidate).permit :name, :email, :phone, :expected_intern, :note, :cv_url, :status
  end
end

app/controllers/trainee/courses_controller.rb
class Trainee::CoursesController < ApplicationController
  layout "trainee_layout"
  before_action :verify_suppervisor_false
  before_action :logged_in_user, except: %i(index)
  before_action :load_course, except: :index
  load_and_authorize_resource

  def index
    unless user_signed_in?
      redirect_to "/introduction"
    else
      @courses = current_user.courses
    end
  end

  def show
    @course_subjects = @course.course_subjects
    @trainers = @course.users.trainers.alphabet_name
    @trainees = @course.users.trainees.alphabet_name
  end


  private

  def load_course
    @course = Course.find_by id: params[:id]
    return if @course
    flash[:danger] = "Oop! Can't found course"
    redirect_to :root
  end
end

app/controllers/trainee/subjects_controller.rb
class Trainee::SubjectsController < ApplicationController
  layout "trainee_layout"
  def show
    @subject = Subject.find params[:subject_id]
    cs = CourseSubject.find_by subject_id: params[:subject_id], course_id: params[:course_id]
    @user_subjects = cs.user_subjects
    @user_subject = UserSubject.find_by user_id: current_user.id, course_subject_id: cs.id
    @user_tasks = @user_subject.user_tasks
  end
end

app/controllers/trainee/user_tasks_controller.rb
class Trainee::UserTasksController < ApplicationController
  before_action :logged_in_user
  before_action :load_user_task
  before_action :verify_subject_must_be_active
  after_action :notify_finish_subject
  def update
    verify_clear_task_in_progress @ut
    unless @user_tasks.blank?
      flash[:danger] = "You must finish task in progress before receiver a new task!"
    else
      if @ut.update_attributes(params_user_task)
        case params[:status]
        when "in_progress"
          @ut.update_attributes date_receive: Time.zone.today
          flash[:success] = "You had been receiver task, let do it! Good Luck"
        else
          @ut.update_attributes date_finish: Time.zone.today
        end
      else
        flash[:danger] = "Sorry, this is error"
      end
    end
    redirect_back fallback_location: root_path
  end

  private

  def notify_finish_subject
    user_subject = @ut.user_subject
    if user_subject.user_tasks.finish.size == user_subject.user_tasks.size
      user_subject.update_attributes status: "finish", date_end: Time.zone.today
      ReportProgressMailer.report_subject(user_subject).deliver_now
      flash[:notify_finish_subject] = t "user_tasks.notify_finish_task"
    end
  end

  def load_user_task
    @ut = UserTask.find_by id: params[:id]
    return if @ut
    flash[:danger] = "update unsuccess"
    redirect_back fallback_location: root_path
  end

  def params_user_task
    params.permit :status
  end

  def verify_subject_must_be_active
    unless @ut.user_subject.course.in_progress?
      flash[:danger] = "Sorry, this course must in progress to report task"
      redirect_back fallback_location: root_path
    end
    unless @ut.user_subject.course_subject.in_progress?
      flash[:danger] = "Sorry, this subject must in progress to report task"
      redirect_back fallback_location: root_path
    end
  end

  def verify_clear_task_in_progress ut
    user_subject = UserSubject.find_by id: ut.user_subject_id
    @user_tasks = user_subject.user_tasks.status_in_progress.not_this ut
  end
end

app/controllers/trainee/users_controller.rb
class Trainee::UsersController < ApplicationController
  layout "trainee_layout"
  before_action :logged_in_user
  before_action :load_user
  load_and_authorize_resource

  private

  def load_user
    user = User.find_by id: params[:id]
    return if user
    flash[:danger] = "Couldn't find user"
    redirect_to root_path
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def style_get_course arg
    case arg
    when "#"
      @style = "flex: 62 0 auto; width: 62px; max-width: 62px;"
    when "Course"
      @style = "flex: 270 0 auto; width: 270px; max-width: 270px;"
    when "Owner"
      @style = "flex: 200 0 auto; width: 200px; max-width: 200px;"
    when "Status"
      @style = "flex: 150 0 auto; width: 150px; max-width: 150px;"
    when "Program"
      @style = "flex: 250 0 auto; width: 250px; max-width: 250px;"
    else
      @style = "flex: 250 0 auto; width: 250px; max-width: 250px;"
    end
  end

  def show_title_index_course option
    case option
    when "2"
      @title = "Courses Join-in"
    when "3"
      @title = "System Courses"
    else
      @title = "My Courses"
    end
  end

  def owner_info course
    @owner = User.find_by id: course.users_id
    @owner ||= User.new
  end

  def select_owner_list
    @trainers = User.trainers
  end

  def org_hash
    @orgs = {DaNang: t("courses._orgs.dn"),
      HaNoi: t("courses._orgs.hn"),
      HoChiMinh: t("courses._orgs.hcm")}
  end

  def display_column_course_index
      %w(# Course Owner ) + Course.column_names -
      %w(id name date_end description created_at updated_at banner avatar users_id date_start training_standard) + %w(Standard)
  end

  def define_stt_index course
    case course.status
    when "init"
      @class = "cursor sttcourse sttcourse-init"
      @status = "Init"
    when "in_progress"
      @class = "cursor sttcourse sttcourse-in-progress"
      @status = "In Progress"
    when "finish"
      @class = "cursor sttcourse sttcourse-finish"
      @status = "Finish"
    else
      @class = "cursor sttcourse sttcourse-close"
      @status = "Block"
    end
  end

  def check_status course
    case true
    when course.init?
      @status = "init"
    when course.in_progress?
      @status = "in_progress"
    when course.finish?
      @status = "finish"
    else
      @status = "block"
    end
    @class = "label-status status-#{@status}"
  end
end

app/views/trainee/courses/_course.html.erb
<div class="col-md-4">
  <div class="widget <%= course.status %>-widget">
    <div class="widget-advanced widget-advanced-alt">
      <div class="widget-header text-center">
        <%= image_tag(course.banner.url, class: "widget-background animation-pulseSlow") %>
        <h4 class="widget-content widget-content-image widget-content-light">
          <%= link_to course.name, trainee_course_view_path(id: course.id),
            class: "themed-color-autumn" %><br>
          <small><%= course.training_standard %></small>
        </h4>
      </div>
      <div class="widget-main">
        <a href="page_ready_user_profile.html" class="widget-image-container animation-hatch">
          <%= image_tag(course.avatar.url, class: "widget-image img-circle") %>
        </a>
        <div class="list-group remove-margin">
          <a href="javascript:void(0)" class="list-group-item">
            <span class="pull-right"><strong><%= course.subjects.size %></strong></span>
            <h4 class="list-group-item-heading remove-margin"><i class="fa fa-file fa-fw"></i> Subjects</h4>
          </a>
          <a href="javascript:void(0)" class="list-group-item">
            <span class="pull-right"><strong><%= course.users.trainers.size %></strong></span>
            <h4 class="list-group-item-heading remove-margin"><i class="fa fa-briefcase fa-fw"></i> Trainers</h4>
            <p class="list-group-item-text"></p>
          </a>
          <a href="javascript:void(0)" class="list-group-item">
            <span class="pull-right"><strong><%= course.users.trainees.size %></strong></span>
            <h4 class="list-group-item-heading remove-margin"><i class="fa fa-users fa-fw"></i> Trainees</h4>
            <p class="list-group-item-text"></p>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trainee/courses/_subject.html.erb
<li>
  <% subject = course_subject.subject %>
  <span class="label timeline-label start_date_label">
    <!-- <% if course_subject.user_subjects.find_by(user_id: current_user.id).date_start.present? %>
      <%= course_subject.user_subjects.find_by(user_id: current_user.id).date_start %>
    <% else %>
      Not activated
    <% end %> -->
    <% if course_subject.date_start.present? %>
      <%= course_subject.date_start %>
    <% else %>
      Not activated
    <% end %>
  </span>
  <div class="subject-timeline subject">
    <!-- <% check_status_cs course_subject.user_subjects.find_by(user_id: current_user.id) %> -->
    <% check_status_cs course_subject %>
    <div class="subject-status-box <%= @status %>-background-color corner-ribbon">
      <%= t "courses._status.#{@status}" %>
    </div>
    <div class="div-status" title=<%= t "courses._status.#{@status}" %>>
      <em class="<%= @class_point %>"></em>
    </div>
    <div class="subject-body clearfix">
      <div class="subject-image">
        <%= image_tag(subject.avatar.url, class: "dp-img-circle") %>
      </div>
      <div class="infor">
        <div>
          <span class="subject-name"><%= link_to subject.name,
            show_subject_in_course_path(@course, subject) %></span>
        </div>
        <div class="td-subject-description">
          <%= subject.description %>
        </div>
      </div>
    </div>
  </div>
  <!-- <% if course_subject.user_subjects.find_by(user_id: current_user.id).finish? %>
    <span class="label timeline-label end_date_label">
       <%= course_subject.user_subjects.find_by(user_id: current_user.id).date_end %>
    </span>
  <% end %> -->
  <% if course_subject.finish? %>
    <span class="label timeline-label end_date_label">
       <%= course_subject.date_end %>
    </span>
  <% end %>
  <div class="clearfix"></div>
</li>

app/views/trainee/courses/_user.html.erb
<p class="text-muted" style="position: relative;">
  <%= image_tag(user.avatar.url, class: "img-member img-circle img-responsive", title: user.name) %>
  <%= link_to user.name, profile_path(user), style: "position: absolute; top: 11px; left: 34px" %>
</p>

app/views/trainee/courses/index.html.erb
<% provide :title, "Courses" %>
<section class="content-header">
  <% show_title_index_course params[:option] %>
  <h1>
    <%= @title %>
    <small>advanced boxs</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to root_path do %><i class="fa fa-dashboard"></i> Home<% end %></li>
    <li class="active">My courses</li>
  </ol>
</section>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="row" style="padding: 20px;">
          <%= render partial: "course", collection: @courses, as: :course %>
        </div>
      </div>
    </div>
  </div>
</section>
<style type="text/css">
.widget-advanced .widget-background {
  position: absolute;
  top: 0;
  left: 0;
  height: 150px;
}
.widget-advanced .widget-content-image {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  padding: 15px;
  padding-top: 25px;
  margin: 0;
  background: url(../img/template/ie8_opacity_dark_60.png) repeat;
  background: rgba(0, 0, 0, 0.79);
}
.widget .widget-content-light {
  color: #ffffff;
}
.themed-color-autumn {
  color: #e67e22 !important;
}
</style>

app/views/trainee/courses/show.html.erb
<% provide :title, @course.name %>
<div class="content-header">
  <ol class="breadcrumb">
    <li><%= link_to root_path do %><i class="fa fa-dashboard"></i> Home<% end %></li>
    <li><%= link_to "My courses", mycourses_path %></li>
    <li class="active"><%= @course.name %></li>
  </ol>
</div>
<div class="dbox">
  <div class="dbox-header clearfix">
    <div class="col-md-12 course-subject">
      <div class="course-header">
        <span class="header-title"><%= @course.name %></span>
        <span class="courses-detail-status">
          <% check_status @course %>
          <span class="<%= @class %>">
            <%= t("courses._status.#{@status}") %>
          </span>
        </span>
        <% owner = User.find(@course.users_id) %>
        <div class="show-creator">
          <%= link_to profile_path(owner), style: "color: white;" do %>
            <%= image_tag(owner.avatar.url, class: "creator-image") %>
            <h4><%= owner.name %></h4>
          <% end %>
        </div>
        <a href="#" id="show-course-description">Show descriptions</a>
        <div id="course-description" style="width: 90%; display: none">
          <%= @course.description %>
        </div>
      </div>
    </div>
  </div>
  <div class="course-menu">
    <ul class="nav nav-tabs course-menu-items">
      <li class="active">
        <a id="active-timeline" data-toggle="tab">
          <i class="fa fa-book"></i> Subjects
        </a>
      </li>
      <li>
        <a id="active-member" data-toggle="tab">
          <i class="fa fa-address-book-o"></i> Members
        </a>
      </li>
    </ul>
  </div>
  <div class="course-show-body">
    <div class="col-md-12 col-list-subjects">
      <div class="course-container content-block active" id="timeline">
        <ul class="timeline timeline-inverse timeline-subject">
          <%= render partial: "subject", collection: @course_subjects, as: :course_subject %>
        </ul>
      </div>
      <div class="content-block" id="member" style="max-height: 100%">
        <div class="box">
          <div class="box-header with-border">
            <h3 class="box-title">
              Members : <%= @trainers.size + @trainees.size %>
            </h3>
            <div class="box-tools pull-right">
            </div>
          </div>
          <div class="box-body">
            <div class="col-md-6">
              <h4>Trainers :  <%= @trainers.size %></h4>
              <%= render partial: "user", collection: @trainers, as: :user%>
            </div>
            <div class="col-md-6">
              <h4>Trainees : <%= @trainees.size %></h4>
              <%= render partial: "user", collection: @trainees, as: :user%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style type="text/css">
  td {
    width: 50%;
    border-right: 1px solid #eee;
  }
  .nav-tabs-custom {
    background: #d4d2d2;
  }
  nav-tabs-custom>.nav-tabs>li.active {
    border-top-color: #3c8dbc;
  }
  .nav-tabs .active a {
      background: rgb(145, 209, 255) !important;
  }
  .content-block {
    display: none;
  }
  .active {
    display: block;
  }
  .img-member{
    width: 30px;
    height: 30px
  }
</style>