config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  devise_for :users, skip: [:sessions], :controllers => {passwords: "passwords", registrations: "users"}
  as :user do
    get "/login", to: "sessions#new", as: :new_user_session
    post "/login", to: "sessions#create", as: :user_session
    delete "/logout", to: "sessions#destroy", as: :destroy_user_session
  end

  as :user do
    delete "/users/:id", to: "users#destroy", as: :user
    patch "/users/:id/block", to: "users#block_user", as: :block_user
    get "/trainer", to: "users#index", as: :user_trainer
    get "/trainee", to: "users#index", as: :user_trainee
    get "/users/:id", to: "users#show"
    # delete "/logout", to: "sessions#destroy", as: :destroy_user_session
  end

  as :course do
    get "/mycourse/:id", to: "trainee/courses#show", as: :trainee_course_view
    get "/mycourses", to: "trainee/courses#index"
    get "/course/new", to: "courses#new", as: :new_course
    patch "/courses/:id/block", to: "courses#block_course", as: :block_course
    get "/courses/:id", to: "courses#show"
    as :subjects do
      get "/mycourse/:course_id/subjects/:subject_id", to: "trainee/subjects#show", as: :show_subject_in_course
      get "/courses/:course_id/subjects/:subject_id", to: "subjects#show_subject_in_course", as: :show_subject_in_course_trainer
    end
  end

  patch "/update_progress/:id", to: "trainee/user_tasks#update", as: :user_task
  root to: "static_pages#home"
  get "/introduction", to: "trainee/candidates#new"
  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"
  resources :subjects
  resources :candidates, except: %i(new create)
  post "candidates", to: "trainee/candidates#create"
  resources :detail_links
  resources :courses
  resources :course_subjects, only: [:create, :update, :destroy, :index]
  resources :user_courses, only: [:create, :update, :destroy, :index]
  patch "/define_action", to: "course_subjects#define_action"
  post "/del_user_courses", to: "user_courses#del_user_courses"
  post "/del_course_subject", to: "course_subjects#del_course_subjects"
  get "/profiles/:id", to: "trainee/users#show", as: :profile
  get "/profiles/:id/edit", to: "profiles#edit", as: :edit_profile
  put "profiles/:id", to: "profiles#update", as: :update_profile
  patch "profiles/:id", to: "profiles#updateAvatar", as: :avatar
  get "/courses/status", to: "courses#change_status", as: :course_status
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :subject
  has_many :user_tasks, dependent: :destroy
  has_many :having_users, through: :user_tasks, source: :user_subject
  has_many :detail_links
  validates :name, presence: true, length: {maximum: 250}
  validates :description, length: {maximum: 5000}
  validate :name_is_only_1_with_a_subject
  scope :has_same_name, ->(name){where name: name.downcase}
  scope :of_subject, ->(subject_id){where subject_id: subject_id}

  def add_user_task user_subject
    having_users << user_subject
  end
  private

  def name_is_only_1_with_a_subject
    return if Task.of_subject(subject_id).pluck(:id).include? id
    return if Task.of_subject(subject_id).has_same_name(name).blank?
    errors.add :name, 'Task name is already in system with this subject'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user
  def new
    @subject = Subject.find_by id: params[:id]
    @task= @subject.tasks.new
  end

  def create
    @task = Task.new params_task
    if @task.save
      save_user_task @task
      @mes_success = 'Task "#{@task.name}" insert into subject "#{@task.subject.name}" successfully'
    else
      @mes_fail = "Can't insert task #{@task.name} into subject #{@task.subject.name}"
    end
  end

  def update
    @task = Task.find params[:id]
    if @task.update_attributes params_task
      @mes_success = 'Update task "#{@task.name}" successfully'
    else
      @mes_fail = "Can't update task #{@task.name} of subject #{@task.subject.name}"
    end
  end

  def edit
    @task = Task.find params[:id]
  end

  private

  def params_task
    params.require(:task).permit :name, :description, :subject_id, :id
  end

  def save_user_task task
    subject = task.subject
    subject.course_subjects.each do |x|
      x.user_subjects.each do |y|
        y.add_task_user task
      end
    end
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
  def define_cancel_task_id task
    if task.id?
      "cancel_task_edit"
    else
      "cancel_task_new"
    end
  end

  def calc_percent user_subject
    total = user_subject.user_tasks.size
    if total != 0
      finish = user_subject.user_tasks.finish.size
      @percent = ((finish.to_f/total) * 100).to_i
    else
      @percent = 100
    end
    if @percent <= 20
      @class = "progress-bar progress-bar-danger"
    elsif @percent<=40
      @class = "progress-bar progress-bar-warning"
    elsif @percent<=60
      @class = "progress-bar progress-bar-info"
    else
      @class = "progress-bar progress-bar-success"
    end
  end
end

app/views/tasks/_detail_link.html.erb
<div class="sortable content-section">
  <div class="profile_top_view">
    <div class="row">
      <div class="col-md-12">
        <h4 class="view-control task-tlt"><%= detail_link.name %></h4>
      </div>
    </div>
  </div>
  <table class="table table_profile">
    <tr>
      <td class="view-field">
        <strong class="view-control">Detail's Link</strong>
      </td>
      <td class="profile_content">
        <a href="<%= detail_link.link %>" target="_blank">
          <%= detail_link.link %>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/tasks/_form.html.erb
<%= form_for @task, :html => {class: "new-section"}, remote: true do |f| %>
  <%= f.hidden_field :subject_id %>
  <div>
    <div class="edit-field block">
      <div class="form-group">
        <%= f.label :name, t("clubs._form.name") %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>
  <div>
    <div class="edit-field block">
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="form-group push-top-md edit-field block">
    <div class="row">
      <div class="col-sm-6"><%= t "clubs._form.require" %></div>
      <div class="col-sm-6 text-right">
        <button id="<%= define_cancel_task_id @task %>" type="button"
          class="btn-cancel btn btn-default" value="<%= @task.id %>">
          Cancel
        </button>
        <%= f.submit "Add", class: "btn-save btn btn-primary btn-load" %>
      </div>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $('#cancel_task_new').click(function(){
    $('#task-add-id').show();
    $('#new_task').remove();
  });
  $('#cancel_task_edit').click(function(){
    var task_id = $('#cancel_task_edit').val();
    $('#edit_task_'+task_id).remove();
    $('#info_task_'+task_id).show();
  });
</script>

app/views/tasks/_index.html.erb
<div class="section-detail section-employment" style="max-height: 613px;">
  <div class="box border-info">
    <fieldset>
      <legend class="box-md">
        <i class="fa fa-fw fa-bank"></i><%= @subject.name %>
        <span class="form-btn-edit">
          <%= link_to edit_subject_path(@subject), class: "btn btn-sm btn-warning" do %>
            <i class="fa fa-cog"></i>
          <% end %>
        </span>
      </legend>
      <% if @tasks.blank? %>
        <div class="placeholder-section box-md">
          <p class="placeholder">This subject hasn't task, let's add some tasks!</p>
        </div>
      <% end %>
      <div id="form-task">
        <div class="sortable content-section section-catalogy">
          <span class="catalogy-espand fa fa-angle-double-right" id="catalogy-link">
          </span>
          <label style="font-size: 20px">Detail Links</label>
        </div>
        <div class="display-none" id="link-content">
          <%= render partial: "tasks/detail_link", collection: @detail_links, as: :detail_link %>
        </div>
        <div class="sortable content-section section-catalogy">
          <span class="catalogy-espand fa fa-angle-double-right" id="catalogy-task">
          </span>
          <label style="font-size: 20px">Tasks</label>
        </div>
        <div class="display-none" id="task-content">
          <%= render partial: "tasks/task", collection: @tasks, as: :task %>
        </div>
      </div>
    </fieldset>
  </div>
</div>

app/views/tasks/_task.html.erb
<div id="info_club_<%= task.id %>" class="sortable content-section">
  <div class="profile_top_view">
    <div class="row">
      <div class="col-md-12">
        <h4 class="view-control task-tlt"><%= task.name %></h4>
      </div>
      <!--
      <div class="col-md-2">
        <% unless current_user.trainee? %>
          <span class="form-btn-edit">
            <%= link_to task, method: :delete, data: {confirm: "Are you sure you want to delete this task?"},
              class: "btn btn-sm btn-danger", remote: true do %>
              <i class="fa fa-trash-o"></i>
            <% end %>
            <%= link_to edit_task_path(task), class: "btn btn-sm btn-warning", remote: true do %>
              <i class="fa fa-pencil"></i>
            <% end %>
          </span>
        <% end %>
      </div>-->
    </div>
  </div>
  <table class="table table_profile">
    <tr>
      <td class="view-field">
        <strong class="view-control">Youtube's Video</strong>
      </td>
      <td class="profile_content">
        <% if task.link_video.present? %>
          <a href="https://www.youtube.com/watch?v=<%= task.link_video %>" target="_blank">
            https://www.youtube.com/watch?v=<%= task.link_video %>
          </a>
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="view-field">
        <strong class="view-control">Description</strong>
      </td>
      <td class="profile_content"><%= task.description %></td>
    </tr>
  </table>
</div>

app/views/tasks/create.js.erb
<% if @task.errors.any? %>
  alertify.error('<%= escape_javascript(render :partial => "shared/error_messages", :locals => {:object => @task })%>');
<% else %>
  $('#new_task').remove();
  alertify.success('<%= @mes_success %>');
  $('#form-task').append('<%= j render(@task) %>');
  $('#task-add-id').show();
<% end %>
$('#img-load').hide();

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/edit.js.erb
$('#task-add-id').hide();
$('#info_task_<%= params[:id] %>').hide().after('<%= j render("tasks/form") %>');

app/views/tasks/new.html.erb
<%= render("form") %>

app/views/tasks/new.js.erb
$('#task-add-id').hide().after('<%= j render("tasks/form") %>');

app/views/tasks/update.js.erb
<% if @task.errors.any? %>
  alertify.error('<%= j (render partial: "shared/error_messages", locals: {object: @task })%>');
<% else %>
  $('#edit_task_<%= params[:id] %>').remove();
  $('#info_task_<%= params[:id] %>').replaceWith('<%= j render(@task) %>').show();
  $('#task-add-id').show();
  alertify.success('<%= @mes_success %>');
<% end %>
$('#img-load').hide();