config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  devise_for :users, skip: [:sessions], :controllers => {passwords: "passwords", registrations: "users"}
  as :user do
    get "/login", to: "sessions#new", as: :new_user_session
    post "/login", to: "sessions#create", as: :user_session
    delete "/logout", to: "sessions#destroy", as: :destroy_user_session
  end

  as :user do
    delete "/users/:id", to: "users#destroy", as: :user
    patch "/users/:id/block", to: "users#block_user", as: :block_user
    get "/trainer", to: "users#index", as: :user_trainer
    get "/trainee", to: "users#index", as: :user_trainee
    get "/users/:id", to: "users#show"
    # delete "/logout", to: "sessions#destroy", as: :destroy_user_session
  end

  as :course do
    get "/mycourse/:id", to: "trainee/courses#show", as: :trainee_course_view
    get "/mycourses", to: "trainee/courses#index"
    get "/course/new", to: "courses#new", as: :new_course
    patch "/courses/:id/block", to: "courses#block_course", as: :block_course
    get "/courses/:id", to: "courses#show"
    as :subjects do
      get "/mycourse/:course_id/subjects/:subject_id", to: "trainee/subjects#show", as: :show_subject_in_course
      get "/courses/:course_id/subjects/:subject_id", to: "subjects#show_subject_in_course", as: :show_subject_in_course_trainer
    end
  end

  patch "/update_progress/:id", to: "trainee/user_tasks#update", as: :user_task
  root to: "static_pages#home"
  get "/introduction", to: "trainee/candidates#new"
  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"
  resources :subjects
  resources :candidates, except: %i(new create)
  post "candidates", to: "trainee/candidates#create"
  resources :detail_links
  resources :courses
  resources :course_subjects, only: [:create, :update, :destroy, :index]
  resources :user_courses, only: [:create, :update, :destroy, :index]
  patch "/define_action", to: "course_subjects#define_action"
  post "/del_user_courses", to: "user_courses#del_user_courses"
  post "/del_course_subject", to: "course_subjects#del_course_subjects"
  get "/profiles/:id", to: "trainee/users#show", as: :profile
  get "/profiles/:id/edit", to: "profiles#edit", as: :edit_profile
  put "profiles/:id", to: "profiles#update", as: :update_profile
  patch "profiles/:id", to: "profiles#updateAvatar", as: :avatar
  get "/courses/status", to: "courses#change_status", as: :course_status
end

app/views/component/profile_component/_boxprofile.html.erb
<div class="box box-primary" id="profile-box" style="max-height: 543px;">
  <div id="profile-content">
    <% if can? :update, @user %>
      <%= link_to edit_profile_path(@user), class: "btn btn-sm btn-default form-btn-edit",
        remote: true do %>
        <i class="fa fa-cog"></i>
      <% end %>

    <% end %>
    <span id="action_block_<%= @user.id %>_2">
      <% if can? :block_user, @user %>
        <% if @user.active? %>
          <%= link_to block_user_path(id: @user.id, status: "block"), method: :patch,
            data: {confirm: "Are you sure to block this user?"}, remote: true,
            class: "btn btn-sm btn-default form-btn-trash" do %>
            <i class="fa fa-unlock"></i>
          <% end %>
        <% else %>
          <%= link_to block_user_path(id: @user.id, status: "active"), method: :patch,
            data: {confirm: "Are you sure to block this user?"}, remote: true,
            class: "btn btn-sm btn-default form-btn-trash" do %>
            <i class="fa fa-lock"></i>
          <% end %>
        <% end %>
      <% end %>
    </span>
    <div class="box-body">
      <p class="text-muted">
        <strong>Name :</strong> <%= @user.name %>
      </p>
      <hr>
      <p class="text-muted">
        <strong>Email :</strong> <%= @user.email %>
      </p>
      <hr>
      <p class="text-muted">
        <strong>Gender :</strong> <%= @user.gender %>
      </p>
      <hr>
      <p class="text-muted">
        <strong>University :</strong> <%= @user.university %>
      </p>
      <hr>
      <p class="text-muted">
        <strong>Program :</strong> <%= @user.program %>
      </p>
      <hr>
      <p class="text-muted">
        <strong>Type :</strong> <%= @user.suppervisor %>
      </p>
      <hr>
      <p class="text-muted">
        <strong>Date Start :</strong> <%= @user.date_start %>
      </p>
      <hr>
    </div>
  </div>
</div>
<style type="text/css">
  .form-btn-edit {
    position: absolute;
    right: 0;
    top: 0;
    z-index: 10;
  }
  .form-btn-trash{
    position: absolute;
    right: 35px;
    top: 0;
    z-index: 10;
  }
</style>