config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  devise_for :users, skip: [:sessions], :controllers => {passwords: "passwords", registrations: "users"}
  as :user do
    get "/login", to: "sessions#new", as: :new_user_session
    post "/login", to: "sessions#create", as: :user_session
    delete "/logout", to: "sessions#destroy", as: :destroy_user_session
  end

  as :user do
    delete "/users/:id", to: "users#destroy", as: :user
    patch "/users/:id/block", to: "users#block_user", as: :block_user
    get "/trainer", to: "users#index", as: :user_trainer
    get "/trainee", to: "users#index", as: :user_trainee
    get "/users/:id", to: "users#show"
    # delete "/logout", to: "sessions#destroy", as: :destroy_user_session
  end

  as :course do
    get "/mycourse/:id", to: "trainee/courses#show", as: :trainee_course_view
    get "/mycourses", to: "trainee/courses#index"
    get "/course/new", to: "courses#new", as: :new_course
    patch "/courses/:id/block", to: "courses#block_course", as: :block_course
    get "/courses/:id", to: "courses#show"
    as :subjects do
      get "/mycourse/:course_id/subjects/:subject_id", to: "trainee/subjects#show", as: :show_subject_in_course
      get "/courses/:course_id/subjects/:subject_id", to: "subjects#show_subject_in_course", as: :show_subject_in_course_trainer
    end
  end

  patch "/update_progress/:id", to: "trainee/user_tasks#update", as: :user_task
  root to: "static_pages#home"
  get "/introduction", to: "trainee/candidates#new"
  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"
  resources :subjects
  resources :candidates, except: %i(new create)
  post "candidates", to: "trainee/candidates#create"
  resources :detail_links
  resources :courses
  resources :course_subjects, only: [:create, :update, :destroy, :index]
  resources :user_courses, only: [:create, :update, :destroy, :index]
  patch "/define_action", to: "course_subjects#define_action"
  post "/del_user_courses", to: "user_courses#del_user_courses"
  post "/del_course_subject", to: "course_subjects#del_course_subjects"
  get "/profiles/:id", to: "trainee/users#show", as: :profile
  get "/profiles/:id/edit", to: "profiles#edit", as: :edit_profile
  put "profiles/:id", to: "profiles#update", as: :update_profile
  patch "profiles/:id", to: "profiles#updateAvatar", as: :avatar
  get "/courses/status", to: "courses#change_status", as: :course_status
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :course_subjects, dependent: :destroy
  has_many :courses, through: :course_subjects
  has_many :tasks, inverse_of: :subject, dependent: :destroy
  has_many :detail_links, inverse_of: :subject, dependent: :destroy
  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :detail_links, reject_if: :all_blank, allow_destroy: true
  validates :name, presence: true, length: {maximum: 250}, uniqueness: {case_sensitive: false}
  validates :description, length: {maximum: 5000}
  validates :teacher, length: {maximum: 250}
  validates :time, presence: true
  default_scope ->{order(name: :asc)}
  scope :without_course, ->(course){where.not id: course.subjects.pluck(:id)}
  scope :search, ->(search){where("name LIKE ?", "%#{search}%")}

  mount_uploader :avatar, AvatarSubjectUploaded
  paginates_per  7
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :logged_in_user
  # before_action :load_subject, only: %i(edit update destroy show)
  load_and_authorize_resource param_method: :params_subejct

  def new
    @subject = Subject.new
    1.times { @subject.tasks.build}
    1.times { @subject.detail_links.build}
  end

  def create
    # @subject = Subject.new params_subejct
    if @subject.save
      flash[:success] = "Success! This subject has been create"
      redirect_to @subject
    else
      flash[:danger] = "Oops! Some error in the create process"
      1.times { @subject.tasks.build}
      1.times { @subject.detail_links.build}
      render :new
    end
  end

  def index
    @subjects = Subject.all.page params[:page]
  end

  def edit
    @subject = Subject.find_by id: params[:id]
  end

  def update
    if @subject.update_attributes params_subejct
      flash[:success] = "Success! This Subject has been update"
      redirect_to @subject
    else
      flash[:danger] = "Oops! Can't update this subject"
      1.times { @subject.tasks.build}
      1.times { @subject.detail_links.build}
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      @mes_success = "Delete #{@subject.name} successfully"
    else
      @mes_fail = "Delete #{@subject.name} unsuccessfully"
    end
  end

  def show
    @courses = @subject.courses
    @tasks = @subject.tasks
    @detail_links = @subject.detail_links
  end

  def show_subject_in_course
    @subject = Subject.find params[:subject_id]
    @course_subject = CourseSubject.find_by subject_id: params[:subject_id], course_id: params[:course_id]
    @user_subjects = @course_subject.user_subjects
    @tasks = @subject.tasks
  end

  private

  def load_subject
    @subject = Subject.find_by id: params[:id]
  end

  def params_subejct
    params.require(:subject).permit(:name, :description, :time,
      detail_links_attributes: [:id, :name, :link, :subject_id, :_destroy],
      tasks_attributes: [:id, :name, :description, :subject_id, :_destroy, :link_video])
  end
end

app/controllers/trainee/subjects_controller.rb
class Trainee::SubjectsController < ApplicationController
  layout "trainee_layout"
  def show
    @subject = Subject.find params[:subject_id]
    cs = CourseSubject.find_by subject_id: params[:subject_id], course_id: params[:course_id]
    @user_subjects = cs.user_subjects
    @user_subject = UserSubject.find_by user_id: current_user.id, course_subject_id: cs.id
    @user_tasks = @user_subject.user_tasks
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
  def display_column_subject_index
    %w(#) + Subject.column_names + %w(Numberdays Tasks) - %w(id created_at updated_at time avatar teacher)
  end

  def style_get_subject arg
    case arg
    when "#"
      @style = "flex: 62 0 auto; width: 62px; max-width: 62px;"
    when "Name"
      @style = "flex: 250 0 auto; width: 250px; max-width: 250px;"
    when "Description"
      @style = "flex: 300 0 auto; width: 300px; max-width: 300px;"
    when "Teacher"
      @style = "flex: 170 0 auto; width: 170px; max-width: 170px;"
    when "Numberdays"
      @style = "flex: 110 0 auto; width: 110px; max-width: 110px;"
    else
      @style = "flex: 62 0 auto; width: 62px; max-width: 62px;"
    end
  end

  def find_cs course, subject
    CourseSubject.find_by(course_id: course.id, subject_id: subject.id)
  end

end

app/views/subjects/_detail_link_fields.html.erb
<div class="form-group nested-fields row">
  <div class="col-md-12">
    <%= f.label :name, "Detail link" %>
  </div>
  <div class="col-md-5">
    <%= f.text_field :name, class: "form-control", placeholder: "Enter detail" %>
  </div>
  <div class="col-md-6">
    <%= f.text_field :link, class: "form-control", placeholder: "Enter detail's link" %>
  </div>
  <div class="col-md-1" style="padding: 0px;">
      <%= link_to_remove_association f do %>
        <i class="fa fa-trash-o" style="font-size: 23px;"></i>
      <% end %>
    </div>
</div>

app/views/subjects/_form.html.erb
<%= form_for @subject, html: {style: "width: 100%;"} do |f| %>
  <div class="col-md-5">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Subject Elements</h3>
      </div>
      <div class="box-body">
        <div class="form-group">
        </div>
        <div class="form-group">
          <label class="control-label" for="val_coursename">Subject Name
            <span class="text-danger">*</span>
          </label>
          <%= f.text_field :name, class: "form-control", placeholder: "Enter name" %>
          <span class="error-message">
            <%= show_errors @subject, :name, "name" %>
          </span>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control", style: "max-width: 100%;", placeholder: "Enter description" %>
          <span class="error-message">
            <%= show_errors @subject, :description, "description" %>
          </span>
        </div>
        <div class="form-group">
          <label class="control-label" for="val_coursename">Number days (Max days to learn this subject)
            <span class="text-danger">*</span>
          </label>
          <%= f.number_field :time, min: 1, value: 1, class: "form-control", style: "width: 30%;" %>
          <span class="error-message">
            <%= show_errors @subject, :time, "time" %>
          </span>
        </div>
        <%= f.fields_for :detail_links do |detail_link| %>
          <%= render 'detail_link_fields', f: detail_link %>
        <% end %>
        <div class="form-group">
          <%= link_to_add_association 'Add detail link', f, :detail_links, class: "btn btn-warning " %>
        </div>
        <div class="col-sm-6">(<strong class="text-red">*</strong>)Existing requirement</div>
      </div>
    </div>
  </div>
  <div class="col-md-7">
    <div class="box box-info">
      <div class="box-header with-border">
        <h3 class="box-title">Task of Subject Element</h3>
      </div>
      <div class="form-horizontal">
        <div class="box-body" style="padding: 0px;">
          <%= f.fields_for :tasks do |task| %>
            <%= render 'task_fields', f: task %>
          <% end %>
          <div class="box-footer" style="background: #3a4364bd">
            <%= link_to_add_association 'Add task', f, :tasks, class: "btn btn-warning " %>
            <%= f.submit yield(:button_text), class: "btn btn-info pull-right", id: "submit" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% task_error_name = show_errors @subject, :"tasks.name", "name" %>
<% task_error_des = show_errors @subject, :"tasks.description", "description" %>
<script type="text/javascript">
  <% if task_error_name.present? %>
    alertify.error('<%= task_error_name %>');
  <% end %>
  <% if task_error_des.present? %>
    alertify.error('<%= task_error_des %>');
  <% end %>
</script>

app/views/subjects/_subject.html.erb
<tr id="subject-<%= subject.id %>">
  <td>
    <% if can? :manage, subject %>
      <%= link_to "", subject, method: :delete, data: {confirm: "Are you sure?"}, class: "fa fa-trash", remote: true %>
      <%= link_to "", edit_subject_path(subject), class: "fa fa-pencil-square-o" %>
    <% end %>
  </td>
  <td>
    <%= link_to subject.name, subject , class: "cursor" %>
  </td>
  <td>
    <div class="cursor"><%= subject.description %></div>
  </td>
  <td>
    <div class="cursor"><%= subject.time %> days</div>
  </td>
  <td>
    <%= subject.tasks.size %>
  </td>
</tr>

app/views/subjects/_task.html.erb
<% @course_subject = course_subject_define(params[:course_id], params[:subject_id]) %>
<div class="info-box ">
  <span class="info-box-icon">
    <%= image_tag(@subject.avatar.url) %>
  </span>
  <div class="info-box-content">
    <div class="info-box-text">
      <%= task.name %>
    </div>
    <% if task.link_video.present? %>
      <button class="fa fa-caret-square-o-right video video-open open<%= task.id %>"
        value = "<%= task.id %>" id= "video-open" ></button>
    <% end %>
    <div class="progress">
      <div class="progress-bar"></div>
    </div>
    <% if task.link_video.present? %>
      <span class="progress-description">
        <div class="video-div" id="video_task<%= task.id %>">
          <iframe id="player<%= task.id %>" width="400" height="300"
            src="https://www.youtube.com/embed/<%= task.link_video %>?enablejsapi=1&version=3&playerapiid=ytplayer" frameborder="0"
            allowfullscreen="true" allowscriptaccess="always"></iframe>
        </div>
      </span>
    <% end %>
  </div>
</div>

app/views/subjects/_task_fields.html.erb
<div class="nested-fields row" style="padding-left: 10px; margin-bottom: 30px;">
  <div>
    <div class="col-xs-5">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="col-xs-5">
      <%= f.label :link_video, "Youtube's code of video" %>
    <a href="https://youtu.be/lRV4kuZEtAY" class="ship-info-ic" data-title="Click HERE to show how to get youtube's code of video" target="_blank"> </a>
      <%= f.text_field :link_video, class: "form-control" %>
    </div>
    <div class="col-xs-2" style="padding-top: 30px;">
      <%= link_to_remove_association f do %>
        <i class="fa fa-trash-o" style="font-size: 23px;"></i>
      <% end %>
    </div>
  </div>
  <div>
    <div class="col-xs-10">
      <%= f.label :description %>
      <%= f.text_area :description, style: "max-width: 100%", class: "form-control" %>
    </div>
  </div>
</div>

app/views/subjects/destroy.js.erb
<% if @mes_success.present? %>
  $('#subject-<%= @subject.id %>').remove();
  alertify.success('<%= @mes_success %>');
<% else %>
  alertify.error('<%= @mes_fail %>');
<% end %>

app/views/subjects/edit.html.erb
<% provide :title,  "Update Subject" %>
<% provide :button_text, "Update" %>
<section class="content-header">
  <h1>
    <%= @subject.name %>
    <small>form edit</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to root_path do %><i class="fa fa-dashboard"></i> Home<% end %></li>
    <li><%= link_to "Subjects", subjects_path %></li>
    <li><%= link_to @subject.name, @subject %></li>
    <li class="active">edit</li>
  </ol>
</section>
<section class="content">
  <div class="row">
    <%= render "form" %>
  </div>
</section>

app/views/subjects/index.html.erb
<% provide :title, "Subject" %>
<section class="content-header">
  <h1>
    System Subjects
    <small>advanced tables</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to root_path do %><i class="fa fa-dashboard"></i> Home<% end %></li>
    <li class="active">Subjects</li>
  </ol>
</section>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Hover Data Table</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <div class="row">
            <div class="col-sm-6"></div>
            <div class="col-sm-6">
              <div id="example1_filter" class="dataTables_filter">
                <label>Search:
                  <input id="myInput" type="search" class="form-control input-sm" placeholder="Search for names.." aria-controls="example1">
                </label>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <table id="example2" class="table table-bordered table-hover dataTable">
                <thead>
                  <% display_column_subject_index.each do |item| %>
                      <th><%= item.capitalize %></th>
                    <% end %>
                </thead>
                <tbody>
                  <%= render partial: "subject", collection: @subjects, as: :subject %>
                </tbody>
              </table>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-5">
              <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">
                <%= page_entries_info @subjects, entry_name: 'subject' %>
              </div>
            </div>
            <div class="col-sm-7">
              <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                <%= paginate @subjects, :outer_window => 3 %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/subjects/index.js.erb
$('#example2 tbody').html('<%= j render partial: "subjects/subject", collection: @subjects, as: :subject %>');
$('#example2_paginate').html('<%= j paginate @subjects %>');
$('#example2_info').html('<%= j page_entries_info @subjects, entry_name: "subject" %>');

app/views/subjects/new.html.erb
<% provide :title,  "Subject Create" %>
<% provide :button_text, "Create" %>
<section class="content-header">
  <h1>
    Subject New
    <small>form add</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to root_path do %><i class="fa fa-dashboard"></i> Home<% end %></li>
    <li class="active">New subject</li>
  </ol>
</section>
<section class="content">
  <div class="row">
    <%= render "form" %>
  </div>
</section>

app/views/subjects/show.html.erb
<% provide(:title, @subject.name) %>
<div class="wrapper" style="background: #fff;">
  <section class="content">
    <div class="col-md-9">
      <%= render "tasks/index" %>
    </div>
    <div class="col-md-3">
      <%= render "component/courses_component/box_course" %>
    </div>
  </section>
</div>

app/views/subjects/show_subject_in_course.html.erb
<% provide(:title, @subject.name) %>
<section class="content-header">
  <div class="title">
    <h3 class="box-title name"><%= @subject.name.upcase %></h3>
    <div class="subject-status clearfix">
      <span class="status <%= @course_subject.status %>"><%= @course_subject.status.upcase %></span>
    </div>
  </div>
  <ol class="breadcrumb" style="top: 0px">
    <li><%= link_to root_path do %><i class="fa fa-dashboard"></i> Home<% end %></li>
    <li><%= link_to "Courses", courses_path %></li>
    <% course = Course.find_by(id: params[:course_id]) %>
    <li><%= link_to course.name.slice(0...15), course, title: course.name %></li>
    <li class="active" title="<%= @subject.name %>"><%= @subject.name.slice(0...15) %>...</li>
  </ol>
</section>
<div class="subject-description" style="margin-left: 15px;">
  <a id="show-details">Show details</a>
  <div id="details" class="details">
    <span><%= @subject.description %></span>
    <h4>References</h4>
    <div>
      <%  @subject.detail_links.each do |x| %>
        <p>
          <strong>[<%= x.name %>]</strong>
          <a href="<%= x.link %>" target="_blank" ><%= x.link %></a>
        </p>
      <% end %>
    </div>
  </div>
</div>
<div class="wrapper" style="background: #fff; height: 587px;">
  <section class="content">
    <div class="row row-cus">
      <div class="col-sm-7">
        <%= render partial: "task", collection: @tasks, as: :task%>
      </div>
      <div class="col-sm-5 chart">
        <div>
          <h4 class="sub-header">Processing Chart
            <small> Total tasks: <%= @tasks.size %></small></h4>
          <%= render partial: "trainee/subjects/process_item", collection: @user_subjects, as: :user_subject%>
        </div>
      </div>
    </div>
  </section>
</div>
<% if flash[:notify_finish_subject].present? %>
  <script type="text/javascript">
    alertify.alert("<%= flash[:notify_finish_subject] %>");
  </script>
<% end %>